# Generated by Django 5.1.1 on 2024-09-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categpries',
            new_name='Categories',
        ),
    ]
